Renamed directories

diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -12,46 +12,34 @@
 if [ x$BASH_VERSION = x ]; then exec /bin/bash $0; fi
 
 # Make sure we're not running as root
-if [ $(whoami) = root ]; then echo "Please don't run as root"; exit 1; fi
+if [ $(whoami) = root ]; then /bin/echo "Please don't run as root"; exit 1; fi
 
-web=https://github.com/Spivoxity/geany-mods/releases/download/v0.3
+web=https://github.com/Spivoxity/geany-mods-1.37/releases/download/rel-1
 arch=$(dpkg --print-architecture)
-gver=spivoxity3
-pkgs="geany-common_1.33-1-${gver}_all.deb geany_1.33-1-${gver}_$arch.deb"
 dir=$(dirname $0)
 
 cd $dir
 
 case $arch in
-    amd64|armhf)
-        echo "Installing for $arch ..."; echo;;
+    amd64|i386|armhf)
+        /bin/echo "Installing for architecture $arch ..."; /bin/echo;;
     *)
-        echo "Can't install for $arch"
+        /bin/echo "Can't install for architecture $arch"
         exit 1
 esac
 
-echo "*** Installing packages"
-sudo apt-get -y install \
-     gcc-arm-none-eabi gdb-arm-none-eabi \
-     pulseview sigrok-firmware-fx2lafw \
-     minicom geany geany-plugin-projectorganizer \
-     python3-pip bsdmainutils
-echo
+/bin/echo "*** Adding APT repository"
+sudo /bin/cp geany-mods.list /etc/apt/sources.list.d/geany-mods.list
+sudo apt-key add geany-mods.gpg.key
+sudo apt-get update
 
-vers=$(dpkg-query -W -f '${Version}\n' geany)
-regexp="-$gver\$"
-if [[ $vers =~ $regexp ]]; then
-    echo "*** Geany is already at version $vers"
-else
-    echo "*** Installing enhanced version of geany"
-    for f in $pkgs; do
-        if ! wget $web/$f -O $f; then
-            echo "Couldn't download $f"; exit 1
-        fi
-    done
-    sudo dpkg -i $pkgs
-fi
-echo
+/bin/echo "*** Installing packages"
+sudo apt-get -y install \
+     geany geany-plugin-projectorganizer \
+     gcc-arm-none-eabi gdb-arm-none-eabi \
+     pulseview sigrok-firmware-fx2lafw minicom \
+     python3-pip bsdmainutils
+/bin/echo
 
 # The Python module cmsis-pack-manager can't be installed on Raspberry
 # Pi, because it depends on a back-end written in Rust for which no
@@ -59,27 +47,28 @@ echo
 # lack of memory.  Pyocd works fine without it; the target interfaces
 # we need are already included.
 
-echo "*** Installing pyocd"
+/bin/echo "*** Installing pyocd"
 tmp=/tmp/pyocd-$$
 # Install pyocd itself without deps
 sudo pip3 install --no-deps pyocd
 # Nuke the dependency on cmsis-pack-manager
-sudo sed -i '/^Requires-Dist: cmsis-pack-manager/d' \
+sudo sed -i -e '/^Requires-Dist: cmsis-pack-manager /d' \
+     -e '/^Requires-Dist: pyocd-pemicro /d' \
      /usr/local/lib/python3.*/dist-packages/pyocd-*.dist-info/METADATA
 # Collect other dependencies
 sed -n '/^Requires-Dist: \([^;]*\)$/s//\1/p' \
     /usr/local/lib/python3.*/dist-packages/pyocd-*.dist-info/METADATA >$tmp
 # Install those dependencies
 sudo pip3 install -r $tmp
-echo
+/bin/echo
 
-echo "*** Associating project files with Geany"
-mkdir -p $HOME/.local/share/applications $HOME/.local/share/mime/packages
-cp application-x-geany-project.xml $HOME/.local/share/mime/packages
-cp geany.desktop $HOME/.local/share/applications
+/bin/echo "*** Associating project files with Geany"
+/bin/mkdir -p $HOME/.local/share/applications $HOME/.local/share/mime/packages
+/bin/cp application-x-geany-project.xml $HOME/.local/share/mime/packages
+/bin/cp geany.desktop $HOME/.local/share/applications
 update-mime-database $HOME/.local/share/mime
 update-desktop-database $HOME/.local/share/applications
-echo
+/bin/echo
 
 set-option () {
     # Like crudini --set, but without the syntax error in new options
@@ -87,15 +76,15 @@ set-option () {
     python3 houdini.py set $1 $2 $3 "$4"
 }
 
-echo "*** Making personalised settings for Geany"
+/bin/echo "*** Making personalised settings for Geany"
 mkdir -p $HOME/.config/geany/filedefs
 geanyexts=$HOME/.config/geany/filetype_extensions.conf 
 set-option $geanyexts Extensions GnuAS ''
 set-option $geanyexts Extensions GnuARM '*.s;*.S;'
-cp filetypes.GnuARM.conf $HOME/.config/geany/filedefs
-echo
+/bin/cp filetypes.GnuARM.conf $HOME/.config/geany/filedefs
+/bin/echo
 
-echo "*** Setting preferences for Geany"
+/bin/echo "*** Setting preferences for Geany"
 geanyconf=$HOME/.config/geany/geany.conf
 
 # Geany: Disable 'Load files from last session'
@@ -112,24 +101,24 @@ fi
 
 # Geany: Select project tab in sidebar
 set-option $geanyconf geany sidebar_page 2
-echo
+/bin/echo
 
 # File manager: Disable 'Show options for removable media' (only on Pi)
 fmconf=$HOME/.config/pcmanfm/LXDE-pi/pcmanfm.conf
 if [ -x /usr/bin/pcmanfm ]; then
-    echo "*** Installing file manager settings"
+    /bin/echo "*** Installing file manager settings"
     set-option $fmconf volume mount_on_startup 1
     set-option $fmconf volume mount_removable 1
     set-option $fmconf volume autorun 0
-    echo
+    /bin/echo
 fi
 
-echo "*** Installing default settings for Minicom"
-cp minirc.dfl $HOME/.minirc.dfl
-echo
+/bin/echo "*** Installing default settings for Minicom"
+/bin/cp minirc.dfl $HOME/.minirc.dfl
+/bin/echo
 
-echo "*** Generating Geany project files"
+/bin/echo "*** Generating Geany project files"
 /bin/bash genproj
-echo
+/bin/echo
 
-echo "*** Done! Please reboot."
+/bin/echo "*** Done! Please reboot."
